import { Tinos} from "next/font/google";
import "./globals.css";

const tinos = Tinos ({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"], // choose weights as per your design
});

export const metadata = {
  title: "LabXCode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Ab poore site me Tinos apply hoga */}
      <body className={`${tinos.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
